In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../data/Prepared/car_data_clean.csv')

In [3]:
df['sale_type'].value_counts()

sale_type
Simple Sale                                                          15052
Direct sale, Installment plan                                          518
Exchange                                                               392
Direct sale, Credit                                                    388
Direct sale, Exchange possible                                         362
                                                                     ...
Credit, Direct sale, Trade-in, Exchange possible                         1
Installment plan, Exchange possible, Credit, Rent                        1
Trade-in, Direct sale, Credit, Leasing                                   1
Leasing, Exchange possible, Direct sale, Credit, Installment plan        1
Rent, Installment plan, Exchange possible, Credit, Direct sale           1
Name: count, Length: 354, dtype: int64

In [4]:
df['url'].drop_duplicates()

0        https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...
1        https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...
2        https://olx.uz/d/obyavlenie/juguli-21011-sotil...
3        https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...
4        https://olx.uz/d/obyavlenie/mazda-626-starushk...
                               ...
48268    https://olx.uz/d/obyavlenie/matiz-vest-satylad...
48269    https://olx.uz/d/obyavlenie/nexia-1-sotiladi-p...
48270    https://olx.uz/d/obyavlenie/ford-pasajer-1991-...
48271    https://olx.uz/d/obyavlenie/matiz-oq-2004-yil-...
48272    https://olx.uz/d/obyavlenie/moshina-sotiladi-m...
Name: url, Length: 48273, dtype: object

In [5]:
df.head()

,url,region,district,price_raw,currency,description,image_url,model_raw,body_type,sale_type,...,brand,price_usd,is_outlier,mileage_raw,mileage_log,mileage_group,engine_volume_raw,engine_volume_l,year_valid,district_clean
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,Jizzakh,Gallaaral,15000000.0,UZS,Mator karobka zadnimos qilingan yili 1979,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2103,Sedan,NaN,...,Lada,1250.0,False,NaN,NaN,NaN,12.0,1.20,True,Gallaaral
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,Namangan,Namangan,15000000.0,UZS,Торг строга укапота машина на ходу полный раб...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2105,Sedan,Simple Sale,...,Lada,1250.0,False,72122.0,11.186128,medium,1.0,1.00,True,Namangan
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,Khorezm,Qorovul,15000000.0,UZS,Mashin toxlangan metan 100 lik bo 14 diska b...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2101,Convertible,NaN,...,Lada,1250.0,False,0.0,NaN,NaN,2103.0,2.10,True,Qorovul
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,Jizzakh,Mardzhanbulak,15000000.0,UZS,31029 96yil matori zor karopka zor magnitafon ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 31029,Station Wagon,NaN,...,GAZ,1250.0,False,560.0,NaN,NaN,105.0,1.05,True,Mardzhanbulak
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Karakalpakstan,Qongirot,15000000.0,UZS,Прадаётсья на запчасти Мазда 626 старушка 1.6 ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 626,Hatchback,Simple Sale,...,Other,1250.0,False,NaN,NaN,NaN,16.0,1.60,True,Qongirot

In [38]:
def foreign_key_maker(df, column, id_make):
    lookup = df[[column]].drop_duplicates().reset_index(drop=True)
    lookup[id_make] = lookup.index + 1

    df = df.merge(lookup, on=column, how='left')

    return df, lookup

df, brand = foreign_key_maker(df, 'brand', 'brand_id')
df, currency = foreign_key_maker(df, 'currency', 'currency_id')
df, condition = foreign_key_maker(df, 'condition', 'condition_id')
df, color = foreign_key_maker(df, 'color', 'color_id')
df, transmission = foreign_key_maker(df, 'transmission', 'transmission_id')
df, fuel_type = foreign_key_maker(df, 'fuel_type', 'fuel_type_id')
df, body_type = foreign_key_maker(df, 'body_type', 'body_type_id')
df, region = foreign_key_maker(df, 'region', 'region_id')
df, district = foreign_key_maker(df, 'district', 'district_id')

In [39]:
df.head()

,url,region,district,price_raw,currency,description,image_url,model_raw,body_type,sale_type,...,district_clean,brand_id,currency_id,condition_id,color_id,transmission_id,fuel_type_id,body_type_id,region_id,district_id
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,Jizzakh,Gallaaral,15000000.0,UZS,Mator karobka zadnimos qilingan yili 1979,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2103,Sedan,NaN,...,Gallaaral,1,1,1,1,1,1,1,1,1
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,Namangan,Namangan,15000000.0,UZS,Торг строга укапота машина на ходу полный раб...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2105,Sedan,Simple Sale,...,Namangan,1,1,2,2,1,1,1,2,2
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,Khorezm,Qorovul,15000000.0,UZS,Mashin toxlangan metan 100 lik bo 14 diska b...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2101,Convertible,NaN,...,Qorovul,1,1,1,3,1,1,2,3,3
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,Jizzakh,Mardzhanbulak,15000000.0,UZS,31029 96yil matori zor karopka zor magnitafon ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 31029,Station Wagon,NaN,...,Mardzhanbulak,2,1,1,3,1,1,3,1,4
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Karakalpakstan,Qongirot,15000000.0,UZS,Прадаётсья на запчасти Мазда 626 старушка 1.6 ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 626,Hatchback,Simple Sale,...,Qongirot,3,1,3,3,1,1,4,4,5

In [40]:
def make_str(df, column):
    df[column] = df[column].str.split(',')
    
    df[column] = df[column].apply(
        lambda x: [i.strip() for i in x] if isinstance(x, list) else x
    )
    
    return df
make_str(df, 'sale_type')
make_str(df, 'additional_options')

,url,region,district,price_raw,currency,description,image_url,model_raw,body_type,sale_type,...,district_clean,brand_id,currency_id,condition_id,color_id,transmission_id,fuel_type_id,body_type_id,region_id,district_id
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,Jizzakh,Gallaaral,15000000.0,UZS,Mator karobka zadnimos qilingan yili 1979,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2103,Sedan,NaN,...,Gallaaral,1,1,1,1,1,1,1,1,1
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,Namangan,Namangan,15000000.0,UZS,Торг строга укапота машина на ходу полный раб...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2105,Sedan,[Simple Sale],...,Namangan,1,1,2,2,1,1,1,2,2
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,Khorezm,Qorovul,15000000.0,UZS,Mashin toxlangan metan 100 lik bo 14 diska b...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2101,Convertible,NaN,...,Qorovul,1,1,1,3,1,1,2,3,3
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,Jizzakh,Mardzhanbulak,15000000.0,UZS,31029 96yil matori zor karopka zor magnitafon ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 31029,Station Wagon,NaN,...,Mardzhanbulak,2,1,1,3,1,1,3,1,4
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Karakalpakstan,Qongirot,15000000.0,UZS,Прадаётсья на запчасти Мазда 626 старушка 1.6 ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 626,Hatchback,[Simple Sale],...,Qongirot,3,1,3,3,1,1,4,4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,https://olx.uz/d/obyavlenie/matiz-vest-satylad...,Karakalpakstan,Hodzheyli,30000000.0,UZS,Описание Матиз вест жылы2009 машын жұрып тұр 3...,https://ninja.data.olxcdn.com,Matiz,Other,[Simple Sale],...,Hodzheyli,6,1,1,3,1,1,5,4,255
48269,https://olx.uz/d/obyavlenie/nexia-1-sotiladi-p...,Bukhara,Bukhara,30000000.0,UZS,Описание Nexia 1 sotiladi yurip turgan moshina...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Nexia,Hatchback,[Simple Sale],...,Bukhara,6,1,4,3,1,1,4,8,10
48270,https://olx.uz/d/obyavlenie/ford-pasajer-1991-...,Navoi,Navoi,30000000.0,UZS,"Описание Yili 1991 4ta yangi balon, kalotka Sa...",https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Transit,Sedan,[Simple Sale],...,Navoi,3,1,1,5,1,4,1,13,59
48271,https://olx.uz/d/obyavlenie/matiz-oq-2004-yil-...,Tashkent,Yashnabad,30000000.0,UZS,Описание Matiz Rangi oq Yili 2004 Holati yaxsh...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Matiz,Hatchback,NaN,...,Yashnabad,6,1,1,3,1,3,4,7,61
48272,https://olx.uz/d/obyavlenie/moshina-sotiladi-m...,Bukhara,Bukhara,30000000.0,UZS,Описание Матиз сотилади састаянаси яхши юриши ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Matiz,Other,[Exchange],...,Bukhara,6,1,1,8,1,1,5,8,10

---

In [41]:
exploded = df[['url','sale_type']].explode('sale_type')

In [42]:
exploded, sale_options = foreign_key_maker(exploded, 'sale_type', 'option_id')

In [43]:
listing_sale_options = exploded[['url', 'option_id']].drop_duplicates()

---

In [44]:
exploded = df[['url','additional_options']].explode('additional_options')

In [45]:
exploded, additional_options = foreign_key_maker(exploded, 'additional_options', 'additional_option_id')

In [46]:
listing_additional_options = exploded[['url', 'additional_option_id']].drop_duplicates()

In [47]:
cars = df[['url', 'brand_id', 'model_raw', 'model_clean', 'car_name', 'year', 'year_valid', 'engine_volume_raw', 'engine_volume_l']]

In [16]:
df.groupby('region')['price_usd'].median().sort_values(ascending=False)

region
Tashkent          7700.0
Karakalpakstan    7663.2
Navoi             6725.0
Khorezm           6666.7
Andijan           6375.0
Bukhara           5500.0
Fergana           5500.0
Kashkadarya       5500.0
Namangan          5500.0
Surkhandarya      5500.0
Jizzakh           5200.0
Samarkand         5000.0
Syrdarya          5000.0
Name: price_usd, dtype: float64

In [15]:
car_listings = df[['url', 'description','price_raw', 'price_usd', 'is_outlier', 'currency_id', 'condition_id', 'color_id', 'transmission_id','fuel_type_id','region_id', 'district_id', 'mileage', 'mileage_log', 'mileage_group', 'owners_count', 'image_url']]

In [ ]:
cars = df[['url', 'brand_id', 'model_raw', 'model_clean', 'car_name', 'year', 'year_valid', 'engine_volume_raw', 'engine_volume_l']]
cars.to_csv('../data/Prepared/cars.csv', index=False)

---
# Making csv files for each table

In [ ]:
brands = brand[['brand_id', 'brand']]
brands=brands.rename(columns={'brand': 'brand_name'})
brands.to_csv('../data/Prepared/brands.csv', index=False)

In [29]:
brands

    brand_id     brand_name
0          1           Lada
1          2            GAZ
2          3          Other
3          4       Moskvich
4          5            ZAZ
5          6         Daewoo
6          7         Nissan
7          8            UAZ
8          9           Audi
9         10           Ford
10        11           Opel
11        12            Kia
12        13     Volkswagen
13        14           Fiat
14        15         Toyota
15        16            BMW
16        17  Mercedes-Benz
17        18      Chevrolet
18        19        Hyundai

In [ ]:
sale_options = sale_options[['option_id', 'sale_type']]
sale_options.to_csv('../data/Prepared/sale_options.csv', index=False)
sale_options

    option_id          sale_type
0           1                NaN
1           2        Simple Sale
2           3            Leasing
3           4        Direct sale
4           5  Exchange possible
5           6           Exchange
6           7   Installment plan
7           8        Installment
8           9               Rent
9          10             Credit
10         11           Trade-in

In [ ]:
additional_options = additional_options[['additional_option_id','additional_options']]
additional_options=additional_options.rename(columns={'additional_options': 'additional_option_name'})
additional_options.to_csv('../data/Prepared/additional_options.csv', index=False)

In [ ]:
additional_options = additional_options.drop_duplicates()
listing_additional_options.to_csv('../data/Prepared/listing_additional_options.csv', index=False)

In [18]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:8228@localhost:5432/cars_db')



def inserter(filepath, table_name):
    df = pd.read_csv(filepath)

    df.to_sql(
        table_name,
        engine,
        if_exists='append',
        index=False
    )

    print(f'Data inserted into {table_name}')

In [ ]:
transmissions = transmission[['transmission_id', 'transmission']].rename(columns={'transmission': 'transmission_name'})
transmissions.to_csv('../data/Prepared/transmissions.csv', index=False)

colors = color[['color_id', 'color']].rename(columns={'color':'color_name'})
colors.to_csv('../data/Prepared/colors.csv', index=False)

conditions = condition[['condition_id', 'condition']].rename(columns={'condition':'condition_name'})
conditions.to_csv('../data/Prepared/conditions.csv',index=False)

districts = district[['district_id', 'district']].rename(columns={'district': 'district_name'})
districts.to_csv('../data/Prepared/districts.csv',index=False)

fuel_types = fuel_type[['fuel_type_id', 'fuel_type']].rename(columns={'fuel_type':'fuel_type_name'})
fuel_types.to_csv('../data/Prepared/fuel_types.csv',index=False)

regions = region[['region_id', 'region']].rename(columns={'region':'region_name'})
regions.to_csv('../data/Prepared/regions.csv',index=False)

currencies = currency[['currency_id', 'currency']].rename(columns={'currency':'currency_name'})
currencies.to_csv('../data/Prepared/currencies.csv',index=False)

inserter('../data/Prepared/brands.csv', 'brands')
inserter('../data/Prepared/conditions.csv', 'conditions')
inserter('../data/Prepared/colors.csv', 'colors')
inserter('../data/Prepared/transmissions.csv', 'transmissions')
inserter('../data/Prepared/fuel_types.csv','fuel_types')
inserter('../data/Prepared/regions.csv', 'regions')
inserter('../data/Prepared/districts.csv', 'districts')
inserter('../data/Prepared/sale_options.csv', 'sale_options')
inserter('../data/Prepared/additional_options.csv', 'additional_options')
inserter('../data/Prepared/cars.csv', 'cars')

In [ ]:
car_listings.to_csv('../data/Prepared/car_listings.csv', index=False)

In [ ]:
inserter('../data/Prepared/cars.csv', 'cars')

Data inserted into cars

In [ ]:
inserter('../data/Prepared/car_listings.csv', 'car_listings')

Data inserted into car_listings

In [ ]:
# additional_options is inserted with the other lookup tables before cars.
inserter('../data/Prepared/listing_additional_options.csv', 'listing_additional_options')

--- 
Inserted currencies

In [ ]:
# currencies.csv is created before the lookup-table inserts.
currencies = currency[['currency_id', 'currency']].rename(columns={'currency':'currency_name'})
currencies.to_csv('../data/Prepared/currencies.csv',index=False)

In [ ]:
# currencies is inserted with the other lookup tables before cars.
inserter('../data/Prepared/currencies.csv', 'currencies')

--- 
Use It later

In [ ]:
listing_sale_options.to_csv('../data/Prepared/listing_sale_options.csv',index=False)

In [ ]:
# Insert listing_additional_options after car_listings.
inserter('../data/Prepared/listing_sale_options.csv', 'listing_sale_options')

In [ ]:
inserter('../data/Prepared/car_listings.csv', 'car_listings')