In [ ]:
import numpy as np
import pandas as pd

In [32]:
df = pd.read_csv('/Users/javohireshonov/Desktop/Study/Projects/Uzbekistan car postings /data/Prepared/car_data_clean.csv')

In [33]:
df['sale_type'].value_counts()

sale_type
Simple Sale                                                          15052
Direct sale, Installment plan                                          518
Exchange                                                               392
Direct sale, Credit                                                    388
Direct sale, Exchange possible                                         362
                                                                     ...
Credit, Direct sale, Trade-in, Exchange possible                         1
Installment plan, Exchange possible, Credit, Rent                        1
Trade-in, Direct sale, Credit, Leasing                                   1
Leasing, Exchange possible, Direct sale, Credit, Installment plan        1
Rent, Installment plan, Exchange possible, Credit, Direct sale           1
Name: count, Length: 354, dtype: int64

In [34]:
df['url'].drop_duplicates()

0        https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...
1        https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...
2        https://olx.uz/d/obyavlenie/juguli-21011-sotil...
3        https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...
4        https://olx.uz/d/obyavlenie/mazda-626-starushk...
                               ...
48268    https://olx.uz/d/obyavlenie/matiz-vest-satylad...
48269    https://olx.uz/d/obyavlenie/nexia-1-sotiladi-p...
48270    https://olx.uz/d/obyavlenie/ford-pasajer-1991-...
48271    https://olx.uz/d/obyavlenie/matiz-oq-2004-yil-...
48272    https://olx.uz/d/obyavlenie/moshina-sotiladi-m...
Name: url, Length: 48273, dtype: object

In [35]:
df.head()

,url,region,district,price_raw,currency,description,image_url,model_raw,body_type,sale_type,...,brand,price_usd,is_outlier,mileage_raw,mileage_log,mileage_group,engine_volume_raw,engine_volume_l,year_valid,district_clean
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,Jizzakh,Gallaaral,15000000.0,UZS,Mator karobka zadnimos qilingan yili 1979,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2103,Sedan,NaN,...,Lada,1250.0,False,NaN,NaN,NaN,12.0,1.20,True,Gallaaral
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,Namangan,Namangan,15000000.0,UZS,Торг строга укапота машина на ходу полный раб...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2105,Sedan,Simple Sale,...,Lada,1250.0,False,72122.0,11.186128,medium,1.0,1.00,True,Namangan
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,Khorezm,Qorovul,15000000.0,UZS,Mashin toxlangan metan 100 lik bo 14 diska b...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2101,Convertible,NaN,...,Lada,1250.0,False,0.0,NaN,NaN,2103.0,2.10,True,Qorovul
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,Jizzakh,Mardzhanbulak,15000000.0,UZS,31029 96yil matori zor karopka zor magnitafon ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 31029,Station Wagon,NaN,...,GAZ,1250.0,False,560.0,NaN,NaN,105.0,1.05,True,Mardzhanbulak
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Karakalpakstan,Qongirot,15000000.0,UZS,Прадаётсья на запчасти Мазда 626 старушка 1.6 ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 626,Hatchback,Simple Sale,...,Other,1250.0,False,NaN,NaN,NaN,16.0,1.60,True,Qongirot

In [36]:
def foreign_key_maker(df, column, id_make):
    lookup = df[[column]].drop_duplicates().reset_index(drop=True)
    lookup[id_make] = lookup.index + 1

    df = df.merge(lookup, on=column, how='left')

    return df, lookup

df, brand = foreign_key_maker(df, 'brand', 'brand_id')
df, currency = foreign_key_maker(df, 'currency', 'currency_id')

In [37]:
df.head()

,url,region,district,price_raw,currency,description,image_url,model_raw,body_type,sale_type,...,is_outlier,mileage_raw,mileage_log,mileage_group,engine_volume_raw,engine_volume_l,year_valid,district_clean,brand_id,currency_id
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,Jizzakh,Gallaaral,15000000.0,UZS,Mator karobka zadnimos qilingan yili 1979,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2103,Sedan,NaN,...,False,NaN,NaN,NaN,12.0,1.20,True,Gallaaral,1,1
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,Namangan,Namangan,15000000.0,UZS,Торг строга укапота машина на ходу полный раб...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2105,Sedan,Simple Sale,...,False,72122.0,11.186128,medium,1.0,1.00,True,Namangan,1,1
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,Khorezm,Qorovul,15000000.0,UZS,Mashin toxlangan metan 100 lik bo 14 diska b...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2101,Convertible,NaN,...,False,0.0,NaN,NaN,2103.0,2.10,True,Qorovul,1,1
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,Jizzakh,Mardzhanbulak,15000000.0,UZS,31029 96yil matori zor karopka zor magnitafon ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 31029,Station Wagon,NaN,...,False,560.0,NaN,NaN,105.0,1.05,True,Mardzhanbulak,2,1
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Karakalpakstan,Qongirot,15000000.0,UZS,Прадаётсья на запчасти Мазда 626 старушка 1.6 ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 626,Hatchback,Simple Sale,...,False,NaN,NaN,NaN,16.0,1.60,True,Qongirot,3,1

In [38]:
def make_str(df, column):
    df[column] = df[column].str.split(',')
    
    df[column] = df[column].apply(
        lambda x: [i.strip() for i in x] if isinstance(x, list) else x
    )
    
    return df
make_str(df, 'sale_type')
make_str(df, 'additional_options')

,url,region,district,price_raw,currency,description,image_url,model_raw,body_type,sale_type,...,is_outlier,mileage_raw,mileage_log,mileage_group,engine_volume_raw,engine_volume_l,year_valid,district_clean,brand_id,currency_id
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,Jizzakh,Gallaaral,15000000.0,UZS,Mator karobka zadnimos qilingan yili 1979,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2103,Sedan,NaN,...,False,NaN,NaN,NaN,12.0,1.20,True,Gallaaral,1,1
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,Namangan,Namangan,15000000.0,UZS,Торг строга укапота машина на ходу полный раб...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2105,Sedan,[Simple Sale],...,False,72122.0,11.186128,medium,1.0,1.00,True,Namangan,1,1
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,Khorezm,Qorovul,15000000.0,UZS,Mashin toxlangan metan 100 lik bo 14 diska b...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2101,Convertible,NaN,...,False,0.0,NaN,NaN,2103.0,2.10,True,Qorovul,1,1
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,Jizzakh,Mardzhanbulak,15000000.0,UZS,31029 96yil matori zor karopka zor magnitafon ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 31029,Station Wagon,NaN,...,False,560.0,NaN,NaN,105.0,1.05,True,Mardzhanbulak,2,1
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Karakalpakstan,Qongirot,15000000.0,UZS,Прадаётсья на запчасти Мазда 626 старушка 1.6 ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 626,Hatchback,[Simple Sale],...,False,NaN,NaN,NaN,16.0,1.60,True,Qongirot,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,https://olx.uz/d/obyavlenie/matiz-vest-satylad...,Karakalpakstan,Hodzheyli,30000000.0,UZS,Описание Матиз вест жылы2009 машын жұрып тұр 3...,https://ninja.data.olxcdn.com,Matiz,Other,[Simple Sale],...,False,3590000.0,NaN,NaN,1111.0,1.11,True,Hodzheyli,6,1
48269,https://olx.uz/d/obyavlenie/nexia-1-sotiladi-p...,Bukhara,Bukhara,30000000.0,UZS,Описание Nexia 1 sotiladi yurip turgan moshina...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Nexia,Hatchback,[Simple Sale],...,False,1234.0,NaN,NaN,15.0,1.50,True,Bukhara,6,1
48270,https://olx.uz/d/obyavlenie/ford-pasajer-1991-...,Navoi,Navoi,30000000.0,UZS,"Описание Yili 1991 4ta yangi balon, kalotka Sa...",https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Transit,Sedan,[Simple Sale],...,False,0.0,NaN,NaN,2.0,2.00,True,Navoi,3,1
48271,https://olx.uz/d/obyavlenie/matiz-oq-2004-yil-...,Tashkent,Yashnabad,30000000.0,UZS,Описание Matiz Rangi oq Yili 2004 Holati yaxsh...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Matiz,Hatchback,NaN,...,False,286000.0,12.563751,very_high,1.0,1.00,True,Yashnabad,6,1
48272,https://olx.uz/d/obyavlenie/moshina-sotiladi-m...,Bukhara,Bukhara,30000000.0,UZS,Описание Матиз сотилади састаянаси яхши юриши ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Matiz,Other,[Exchange],...,False,300000.0,12.611541,very_high,38.0,3.80,True,Bukhara,6,1

In [39]:
exploded = df[['url','sale_type']].explode('sale_type')

In [40]:
exploded, sale_options = foreign_key_maker(exploded, 'sale_type', 'option_id')

In [41]:
listing_sale_options = exploded[['url', 'option_id']].drop_duplicates()

In [42]:
df

,url,region,district,price_raw,currency,description,image_url,model_raw,body_type,sale_type,...,is_outlier,mileage_raw,mileage_log,mileage_group,engine_volume_raw,engine_volume_l,year_valid,district_clean,brand_id,currency_id
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,Jizzakh,Gallaaral,15000000.0,UZS,Mator karobka zadnimos qilingan yili 1979,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2103,Sedan,NaN,...,False,NaN,NaN,NaN,12.0,1.20,True,Gallaaral,1,1
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,Namangan,Namangan,15000000.0,UZS,Торг строга укапота машина на ходу полный раб...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2105,Sedan,[Simple Sale],...,False,72122.0,11.186128,medium,1.0,1.00,True,Namangan,1,1
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,Khorezm,Qorovul,15000000.0,UZS,Mashin toxlangan metan 100 lik bo 14 diska b...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2101,Convertible,NaN,...,False,0.0,NaN,NaN,2103.0,2.10,True,Qorovul,1,1
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,Jizzakh,Mardzhanbulak,15000000.0,UZS,31029 96yil matori zor karopka zor magnitafon ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 31029,Station Wagon,NaN,...,False,560.0,NaN,NaN,105.0,1.05,True,Mardzhanbulak,2,1
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Karakalpakstan,Qongirot,15000000.0,UZS,Прадаётсья на запчасти Мазда 626 старушка 1.6 ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 626,Hatchback,[Simple Sale],...,False,NaN,NaN,NaN,16.0,1.60,True,Qongirot,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,https://olx.uz/d/obyavlenie/matiz-vest-satylad...,Karakalpakstan,Hodzheyli,30000000.0,UZS,Описание Матиз вест жылы2009 машын жұрып тұр 3...,https://ninja.data.olxcdn.com,Matiz,Other,[Simple Sale],...,False,3590000.0,NaN,NaN,1111.0,1.11,True,Hodzheyli,6,1
48269,https://olx.uz/d/obyavlenie/nexia-1-sotiladi-p...,Bukhara,Bukhara,30000000.0,UZS,Описание Nexia 1 sotiladi yurip turgan moshina...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Nexia,Hatchback,[Simple Sale],...,False,1234.0,NaN,NaN,15.0,1.50,True,Bukhara,6,1
48270,https://olx.uz/d/obyavlenie/ford-pasajer-1991-...,Navoi,Navoi,30000000.0,UZS,"Описание Yili 1991 4ta yangi balon, kalotka Sa...",https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Transit,Sedan,[Simple Sale],...,False,0.0,NaN,NaN,2.0,2.00,True,Navoi,3,1
48271,https://olx.uz/d/obyavlenie/matiz-oq-2004-yil-...,Tashkent,Yashnabad,30000000.0,UZS,Описание Matiz Rangi oq Yili 2004 Holati yaxsh...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Matiz,Hatchback,NaN,...,False,286000.0,12.563751,very_high,1.0,1.00,True,Yashnabad,6,1
48272,https://olx.uz/d/obyavlenie/moshina-sotiladi-m...,Bukhara,Bukhara,30000000.0,UZS,Описание Матиз сотилади састаянаси яхши юриши ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Matiz,Other,[Exchange],...,False,300000.0,12.611541,very_high,38.0,3.80,True,Bukhara,6,1

In [ ]:
 = df[['url','additional_options']].explode('additional_options')

,url,additional_options
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,NaN
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,NaN
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,NaN
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,NaN
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Customs Cleared
...,...,...
48269,https://olx.uz/d/obyavlenie/nexia-1-sotiladi-p...,Electrical Mirrors
48269,https://olx.uz/d/obyavlenie/nexia-1-sotiladi-p...,Electrical Window Lifters
48270,https://olx.uz/d/obyavlenie/ford-pasajer-1991-...,NaN
48271,https://olx.uz/d/obyavlenie/matiz-oq-2004-yil-...,NaN
48272,https://olx.uz/d/obyavlenie/moshina-sotiladi-m...,Air Conditioner

In [ ]:
exploded, additional_options = foreign_key_maker(exploded, 'additional_options', 'option_id')