In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/Users/javohireshonov/Desktop/Study/Projects/Uzbekistan car postings /data/Prepared/car_data_clean.csv')

In [3]:
df['sale_type'].value_counts()

sale_type
Simple Sale                                                          15052
Direct sale, Installment plan                                          518
Exchange                                                               392
Direct sale, Credit                                                    388
Direct sale, Exchange possible                                         362
                                                                     ...
Credit, Direct sale, Trade-in, Exchange possible                         1
Installment plan, Exchange possible, Credit, Rent                        1
Trade-in, Direct sale, Credit, Leasing                                   1
Leasing, Exchange possible, Direct sale, Credit, Installment plan        1
Rent, Installment plan, Exchange possible, Credit, Direct sale           1
Name: count, Length: 354, dtype: int64

In [4]:
df['url'].drop_duplicates()

0        https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...
1        https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...
2        https://olx.uz/d/obyavlenie/juguli-21011-sotil...
3        https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...
4        https://olx.uz/d/obyavlenie/mazda-626-starushk...
                               ...
48268    https://olx.uz/d/obyavlenie/matiz-vest-satylad...
48269    https://olx.uz/d/obyavlenie/nexia-1-sotiladi-p...
48270    https://olx.uz/d/obyavlenie/ford-pasajer-1991-...
48271    https://olx.uz/d/obyavlenie/matiz-oq-2004-yil-...
48272    https://olx.uz/d/obyavlenie/moshina-sotiladi-m...
Name: url, Length: 48273, dtype: object

In [5]:
df.head()

,url,region,district,price_raw,currency,description,image_url,model_raw,body_type,sale_type,...,brand,price_usd,is_outlier,mileage_raw,mileage_log,mileage_group,engine_volume_raw,engine_volume_l,year_valid,district_clean
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,Jizzakh,Gallaaral,15000000.0,UZS,Mator karobka zadnimos qilingan yili 1979,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2103,Sedan,NaN,...,Lada,1250.0,False,NaN,NaN,NaN,12.0,1.20,True,Gallaaral
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,Namangan,Namangan,15000000.0,UZS,Торг строга укапота машина на ходу полный раб...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2105,Sedan,Simple Sale,...,Lada,1250.0,False,72122.0,11.186128,medium,1.0,1.00,True,Namangan
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,Khorezm,Qorovul,15000000.0,UZS,Mashin toxlangan metan 100 lik bo 14 diska b...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2101,Convertible,NaN,...,Lada,1250.0,False,0.0,NaN,NaN,2103.0,2.10,True,Qorovul
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,Jizzakh,Mardzhanbulak,15000000.0,UZS,31029 96yil matori zor karopka zor magnitafon ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 31029,Station Wagon,NaN,...,GAZ,1250.0,False,560.0,NaN,NaN,105.0,1.05,True,Mardzhanbulak
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Karakalpakstan,Qongirot,15000000.0,UZS,Прадаётсья на запчасти Мазда 626 старушка 1.6 ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 626,Hatchback,Simple Sale,...,Other,1250.0,False,NaN,NaN,NaN,16.0,1.60,True,Qongirot

In [6]:
def foreign_key_maker(df, column, id_make):
    lookup = df[[column]].drop_duplicates().reset_index(drop=True)
    lookup[id_make] = lookup.index + 1

    df = df.merge(lookup, on=column, how='left')

    return df, lookup

df, brand = foreign_key_maker(df, 'brand', 'brand_id')
df, currency = foreign_key_maker(df, 'currency', 'currency_id')
df, condition = foreign_key_maker(df, 'condition', 'condition_id')
df, color = foreign_key_maker(df, 'color', 'color_id')
df, transmission = foreign_key_maker(df, 'transmission', 'transmission_id')
df, fuel_type = foreign_key_maker(df, 'fuel_type', 'fuel_type_id')
df, body_type = foreign_key_maker(df, 'body_type', 'body_type_id')
df, region = foreign_key_maker(df, 'region', 'region_id')
df, district = foreign_key_maker(df, 'district', 'district_id')

In [7]:
df.head()

,url,region,district,price_raw,currency,description,image_url,model_raw,body_type,sale_type,...,district_clean,brand_id,currency_id,condition_id,color_id,transmission_id,fuel_type_id,body_type_id,region_id,district_id
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,Jizzakh,Gallaaral,15000000.0,UZS,Mator karobka zadnimos qilingan yili 1979,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2103,Sedan,NaN,...,Gallaaral,1,1,1,1,1,1,1,1,1
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,Namangan,Namangan,15000000.0,UZS,Торг строга укапота машина на ходу полный раб...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2105,Sedan,Simple Sale,...,Namangan,1,1,2,2,1,1,1,2,2
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,Khorezm,Qorovul,15000000.0,UZS,Mashin toxlangan metan 100 lik bo 14 diska b...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2101,Convertible,NaN,...,Qorovul,1,1,1,3,1,1,2,3,3
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,Jizzakh,Mardzhanbulak,15000000.0,UZS,31029 96yil matori zor karopka zor magnitafon ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 31029,Station Wagon,NaN,...,Mardzhanbulak,2,1,1,3,1,1,3,1,4
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Karakalpakstan,Qongirot,15000000.0,UZS,Прадаётсья на запчасти Мазда 626 старушка 1.6 ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 626,Hatchback,Simple Sale,...,Qongirot,3,1,3,3,1,1,4,4,5

In [8]:
def make_str(df, column):
    df[column] = df[column].str.split(',')
    
    df[column] = df[column].apply(
        lambda x: [i.strip() for i in x] if isinstance(x, list) else x
    )
    
    return df
make_str(df, 'sale_type')
make_str(df, 'additional_options')

,url,region,district,price_raw,currency,description,image_url,model_raw,body_type,sale_type,...,district_clean,brand_id,currency_id,condition_id,color_id,transmission_id,fuel_type_id,body_type_id,region_id,district_id
0,https://olx.uz/d/obyavlenie/vaz-2103-gazda-yur...,Jizzakh,Gallaaral,15000000.0,UZS,Mator karobka zadnimos qilingan yili 1979,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2103,Sedan,NaN,...,Gallaaral,1,1,1,1,1,1,1,1,1
1,https://olx.uz/d/obyavlenie/vaz2105zhuguli-god...,Namangan,Namangan,15000000.0,UZS,Торг строга укапота машина на ходу полный раб...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2105,Sedan,[Simple Sale],...,Namangan,1,1,2,2,1,1,1,2,2
2,https://olx.uz/d/obyavlenie/juguli-21011-sotil...,Khorezm,Qorovul,15000000.0,UZS,Mashin toxlangan metan 100 lik bo 14 diska b...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 2101,Convertible,NaN,...,Qorovul,1,1,1,3,1,1,2,3,3
3,https://olx.uz/d/obyavlenie/waxzod-kafolati-bi...,Jizzakh,Mardzhanbulak,15000000.0,UZS,31029 96yil matori zor karopka zor magnitafon ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 31029,Station Wagon,NaN,...,Mardzhanbulak,2,1,1,3,1,1,3,1,4
4,https://olx.uz/d/obyavlenie/mazda-626-starushk...,Karakalpakstan,Qongirot,15000000.0,UZS,Прадаётсья на запчасти Мазда 626 старушка 1.6 ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,: 626,Hatchback,[Simple Sale],...,Qongirot,3,1,3,3,1,1,4,4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,https://olx.uz/d/obyavlenie/matiz-vest-satylad...,Karakalpakstan,Hodzheyli,30000000.0,UZS,Описание Матиз вест жылы2009 машын жұрып тұр 3...,https://ninja.data.olxcdn.com,Matiz,Other,[Simple Sale],...,Hodzheyli,6,1,1,3,1,1,5,4,255
48269,https://olx.uz/d/obyavlenie/nexia-1-sotiladi-p...,Bukhara,Bukhara,30000000.0,UZS,Описание Nexia 1 sotiladi yurip turgan moshina...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Nexia,Hatchback,[Simple Sale],...,Bukhara,6,1,4,3,1,1,4,8,10
48270,https://olx.uz/d/obyavlenie/ford-pasajer-1991-...,Navoi,Navoi,30000000.0,UZS,"Описание Yili 1991 4ta yangi balon, kalotka Sa...",https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Transit,Sedan,[Simple Sale],...,Navoi,3,1,1,5,1,4,1,13,59
48271,https://olx.uz/d/obyavlenie/matiz-oq-2004-yil-...,Tashkent,Yashnabad,30000000.0,UZS,Описание Matiz Rangi oq Yili 2004 Holati yaxsh...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Matiz,Hatchback,NaN,...,Yashnabad,6,1,1,3,1,3,4,7,61
48272,https://olx.uz/d/obyavlenie/moshina-sotiladi-m...,Bukhara,Bukhara,30000000.0,UZS,Описание Матиз сотилади састаянаси яхши юриши ...,https://frankfurt.apollo.olxcdn.com:443/v1/fil...,Matiz,Other,[Exchange],...,Bukhara,6,1,1,8,1,1,5,8,10

---

In [9]:
exploded = df[['url','sale_type']].explode('sale_type')

In [10]:
exploded, sale_options = foreign_key_maker(exploded, 'sale_type', 'option_id')

In [11]:
listing_sale_options = exploded[['url', 'option_id']].drop_duplicates()

---

In [12]:
exploded = df[['url','additional_options']].explode('additional_options')

In [13]:
exploded, additional_options = foreign_key_maker(exploded, 'additional_options', 'additional_option_id')

In [14]:
listing_additional_options = exploded[['url', 'additional_option_id']].drop_duplicates()

In [15]:
cars = df[['url', 'brand_id', 'model_raw', 'model_clean', 'car_name', 'year', 'year_valid', 'engine_volume_raw', 'engine_volume_l']]

In [16]:
df.groupby('region')['price_usd'].median().sort_values(ascending=False)

region
Tashkent          7700.0
Karakalpakstan    7663.2
Navoi             6725.0
Khorezm           6666.7
Andijan           6375.0
Bukhara           5500.0
Fergana           5500.0
Kashkadarya       5500.0
Namangan          5500.0
Surkhandarya      5500.0
Jizzakh           5200.0
Samarkand         5000.0
Syrdarya          5000.0
Name: price_usd, dtype: float64

In [17]:
car_listings = df[['url', 'description','price_raw', 'price_usd', 'is_outlier', 'currency_id', 'condition_id', 'color_id', 'transmission_id','fuel_type_id','region_id', 'region_id', 'mileage', 'mileage_log', 'mileage_group', 'owners_count', 'image_url']]

In [18]:
df['engine_volume_l'].describe()

count    42640.000000
mean         1.673977
std          0.922089
min          1.000000
25%          1.000000
50%          1.500000
75%          1.800000
max          6.000000
Name: engine_volume_l, dtype: float64

---
# Making csv files for each table

In [22]:
brands = brand[['brand_id', 'brand']]
brands=brands.rename(columns={'brand': 'brand_name'})
brands.to_csv('/Users/javohireshonov/Desktop/Study/Projects/Uzbekistan car postings /data/Prepared/brands.csv', index=False)

In [29]:
brands

    brand_id     brand_name
0          1           Lada
1          2            GAZ
2          3          Other
3          4       Moskvich
4          5            ZAZ
5          6         Daewoo
6          7         Nissan
7          8            UAZ
8          9           Audi
9         10           Ford
10        11           Opel
11        12            Kia
12        13     Volkswagen
13        14           Fiat
14        15         Toyota
15        16            BMW
16        17  Mercedes-Benz
17        18      Chevrolet
18        19        Hyundai

In [33]:
sale_options = sale_options[['option_id', 'sale_type']]
sale_options.to_csv('/Users/javohireshonov/Desktop/Study/Projects/Uzbekistan car postings /data/Prepared/sale_options.csv', index=False)
sale_options

    option_id          sale_type
0           1                NaN
1           2        Simple Sale
2           3            Leasing
3           4        Direct sale
4           5  Exchange possible
5           6           Exchange
6           7   Installment plan
7           8        Installment
8           9               Rent
9          10             Credit
10         11           Trade-in

In [ ]:
additional_options = additional_options[['additional_option_id','additional_options']]
additional_options=additional_options.rename(columns={'additional_options': 'additional_option_name'})
additional_options.to_csv('/Users/javohireshonov/Desktop/Study/Projects/Uzbekistan car postings /data/Prepared/additional_options.csv', index=False)

In [55]:
additional_options = additional_options.drop_duplicates()
listing_additional_options.to_csv('/Users/javohireshonov/Desktop/Study/Projects/Uzbekistan car postings /data/Prepared/listing_additional_options.csv', index=False)

In [42]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:8228@localhost:5432/cars_db')



def inserter(filepath, table_name):
    df = pd.read_csv(filepath)

    df.to_sql(
        table_name,
        engine,
        if_exists='append',
        index=False
    )

    print(f'Data inserted into {table_name}')

In [57]:
inserter('/Users/javohireshonov/Desktop/Study/Projects/Uzbekistan car postings /data/Prepared/additional_options.csv' ,"additional_options")

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "additional_options_pkey"
DETAIL:  Key (additional_option_id)=(1) already exists.

[SQL: INSERT INTO additional_options (additional_option_id, additional_option_name) VALUES (%(additional_option_id__0)s, %(additional_option_name__0)s), (%(additional_option_id__1)s, %(additional_option_name__1)s), (%(additional_option_id__2)s, %(additiona ... 167 characters truncated ... d__5)s, %(additional_option_name__5)s), (%(additional_option_id__6)s, %(additional_option_name__6)s)]
[parameters: {'additional_option_id__0': 1, 'additional_option_name__0': None, 'additional_option_id__1': 2, 'additional_option_name__1': 'Customs Cleared', 'additional_option_id__2': 3, 'additional_option_name__2': 'Electrical Window Lifters', 'additional_option_id__3': 4, 'additional_option_name__3': 'Парктроник', 'additional_option_id__4': 5, 'additional_option_name__4': 'Electrical Mirrors', 'additional_option_id__5': 6, 'additional_option_name__5': 'Air Conditioner', 'additional_option_id__6': 7, 'additional_option_name__6': 'Security System'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [58]:
inserter('/Users/javohireshonov/Desktop/Study/Projects/Uzbekistan car postings /data/Prepared/listing_additional_options.csv', 'listing_additional_options')

IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "listing_additional_options" violates foreign key constraint "listing_additional_options_url_fkey"
DETAIL:  Key (url)=(https://olx.uz/d/obyavlenie/vaz-2103-gazda-yuradi-ID3HdLc.html) is not present in table "car_listings".

[SQL: INSERT INTO listing_additional_options (url, additional_option_id) VALUES (%(url__0)s, %(additional_option_id__0)s), (%(url__1)s, %(additional_option_id__1)s), (%(url__2)s, %(additional_option_id__2)s), (%(url__3)s, %(additional_option_id__3)s), (%(u ... 46502 characters truncated ... 997)s), (%(url__998)s, %(additional_option_id__998)s), (%(url__999)s, %(additional_option_id__999)s)]
[parameters: {'url__0': 'https://olx.uz/d/obyavlenie/vaz-2103-gazda-yuradi-ID3HdLc.html', 'additional_option_id__0': 1, 'url__1': 'https://olx.uz/d/obyavlenie/vaz2105zhuguli-god-vupusk-1982-ID3OIfD.html', 'additional_option_id__1': 1, 'url__2': 'https://olx.uz/d/obyavlenie/juguli-21011-sotiladi-ID3F9wE.html', 'additional_option_id__2': 1, 'url__3': 'https://olx.uz/d/obyavlenie/waxzod-kafolati-bilan-1000-ID3nSNU.html', 'additional_option_id__3': 1, 'url__4': 'https://olx.uz/d/obyavlenie/mazda-626-starushka-1986-ID3Ue7D.html', 'additional_option_id__4': 2, 'url__5': 'https://olx.uz/d/obyavlenie/mazda-626-starushka-1986-ID3Ue7D.html', 'additional_option_id__5': 3, 'url__6': 'https://olx.uz/d/obyavlenie/mazda-626-starushka-1986-ID3Ue7D.html', 'additional_option_id__6': 4, 'url__7': 'https://olx.uz/d/obyavlenie/09-mashina-xolati-yaxshi-ID3V0rE.html', 'additional_option_id__7': 1, 'url__8': 'https://olx.uz/d/obyavlenie/lada-08-sotiladi-ID3ftkn.html', 'additional_option_id__8': 2, 'url__9': 'https://olx.uz/d/obyavlenie/lada-08-sotiladi-ID3ftkn.html', 'additional_option_id__9': 5, 'url__10': 'https://olx.uz/d/obyavlenie/hahhahahahsjjsjsjsj-ID3V0hj.html', 'additional_option_id__10': 6, 'url__11': 'https://olx.uz/d/obyavlenie/jiguli-2107-zor-ID3Y2RC.html', 'additional_option_id__11': 1, 'url__12': 'https://olx.uz/d/obyavlenie/volga-21-sotiladi-ID3ZZSm.html', 'additional_option_id__12': 1, 'url__13': 'https://olx.uz/d/obyavlenie/lada-2108-satiladi-ID3pZH1.html', 'additional_option_id__13': 1, 'url__14': 'https://olx.uz/d/obyavlenie/moshinchaga-garantya-ID3ytoa.html', 'additional_option_id__14': 2, 'url__15': 'https://olx.uz/d/obyavlenie/moshinani-holati-zr-ID3yssJ.html', 'additional_option_id__15': 1, 'url__16': 'https://olx.uz/d/obyavlenie/juguliy-satiladi-ID3MPEI.html', 'additional_option_id__16': 1, 'url__17': 'https://olx.uz/d/obyavlenie/tavriya-zaz-1102-ID3ucZD.html', 'additional_option_id__17': 1, 'url__18': 'https://olx.uz/d/obyavlenie/kafolat-muddati-1-oy-ID3AKpv.html', 'additional_option_id__18': 1, 'url__19': 'https://olx.uz/d/obyavlenie/va2106-sotiladi-1979-yil-ID3ZVXG.html', 'additional_option_id__19': 4, 'url__20': 'https://olx.uz/d/obyavlenie/moshinni-xolati-yaxshi-rangi-maloshniy-yili-1988-yil-4ta-balon-yang-ID3WVT4.html', 'additional_option_id__20': 1, 'url__21': 'https://olx.uz/d/obyavlenie/volga-gaz-24-pikap-mator-kilindi-obmen-bor-boshka-mashinalarga-ID3pVrN.html', 'additional_option_id__21': 2, 'url__22': 'https://olx.uz/d/obyavlenie/moskvich-izh-kombi-ID34ODl.html', 'additional_option_id__22': 2, 'url__23': 'https://olx.uz/d/obyavlenie/moshina-zhiguli-1975-goda-ID38ufV.html', 'additional_option_id__23': 2, 'url__24': 'https://olx.uz/d/obyavlenie/gaz-31029volga-1993-yil-ID3U9mD.html', 'additional_option_id__24': 1 ... 1900 parameters truncated ... 'url__975': 'https://olx.uz/d/obyavlenie/moskvich-412-pikap-dokumentalnyy-yili-1987-propanda-ID3VGqD.html', 'additional_option_id__975': 1, 'url__976': 'https://olx.uz/d/obyavlenie/vaz-21099-sotiladi-ID40vRJ.html', 'additional_option_id__976': 2, 'url__977': 'https://olx.uz/d/obyavlenie/07-juguli-2004-yil-ID3YCsE.html', 'additional_option_id__977': 6, 'url__978': 'https://olx.uz/d/obyavlenie/zhiguli-sotiladi-holati-yahshi-ID376Mb.html', 'additional_option_id__978': 1, 'url__979': 'https://olx.uz/d/obyavlenie/moskvchi-412-sotiladi-ID3LtB4.html', 'additional_option_id__979': 1, 'url__980': 'https://olx.uz/d/obyavlenie/olgan-odam-baraka-topadi-ID3P9Rb.html', 'additional_option_id__980': 1, 'url__981': 'https://olx.uz/d/obyavlenie/moskvich-412-ID399Zj.html', 'additional_option_id__981': 7, 'url__982': 'https://olx.uz/d/obyavlenie/vaz-2101-sotiladi-yli-1985-piropanga-ID3SRCF.html', 'additional_option_id__982': 7, 'url__983': 'https://olx.uz/d/obyavlenie/gaz-24-sotiladi-yili-1985-ID3FDAQ.html', 'additional_option_id__983': 1, 'url__984': 'https://olx.uz/d/obyavlenie/tiko-tez-va-arzon-sotiladi-ID40q2N.html', 'additional_option_id__984': 1, 'url__985': 'https://olx.uz/d/obyavlenie/neksiya-sotiladi-holati-yahshi-1997-yil-ID3YLF0.html', 'additional_option_id__985': 5, 'url__986': 'https://olx.uz/d/obyavlenie/neksiya-sotiladi-holati-yahshi-1997-yil-ID3YLF0.html', 'additional_option_id__986': 2, 'url__987': 'https://olx.uz/d/obyavlenie/srochna-sotiladi-ID3dPUU.html', 'additional_option_id__987': 1, 'url__988': 'https://olx.uz/d/obyavlenie/gaz-volga-21-sotiladi-ID3mgEJ.html', 'additional_option_id__988': 1, 'url__989': 'https://olx.uz/d/obyavlenie/tiko-sotiladi-holati-idealniy-ID3u5ry.html', 'additional_option_id__989': 7, 'url__990': 'https://olx.uz/d/obyavlenie/21011jiguli-xolati-yaxshi-ID3z2ha.html', 'additional_option_id__990': 1, 'url__991': 'https://olx.uz/d/obyavlenie/zhuguli2101-god71-ID3Bfvj.html', 'additional_option_id__991': 1, 'url__992': 'https://olx.uz/d/obyavlenie/sastayana-narmalniy-ID3VniT.html', 'additional_option_id__992': 1, 'url__993': 'https://olx.uz/d/obyavlenie/lada-21099-srochno-ID3SG5D.html', 'additional_option_id__993': 2, 'url__994': 'https://olx.uz/d/obyavlenie/lada-zhiguli-2106-ID3VapC.html', 'additional_option_id__994': 1, 'url__995': 'https://olx.uz/d/obyavlenie/daewoo-tico-1999-ID40gee.html', 'additional_option_id__995': 1, 'url__996': 'https://olx.uz/d/obyavlenie/maskivich-sotiladi-ID3Ba8Y.html', 'additional_option_id__996': 1, 'url__997': 'https://olx.uz/d/obyavlenie/jiggling-06-sotiladi-ID36SZ6.html', 'additional_option_id__997': 3, 'url__998': 'https://olx.uz/d/obyavlenie/zhiguli-vaz-2106-holati-zor-ID3DgJ6.html', 'additional_option_id__998': 1, 'url__999': 'https://olx.uz/d/obyavlenie/tiko-sotiladi-arzon-ID3Yh72.html', 'additional_option_id__999': 5}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)